{% set name = "djangocms-text-ckeditor" %}
{% set version = "5.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a30d92e052643b4dfb4149007f71617959763b805a2f0d4f492095441865457d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - django-cms >=3.6
    - html5lib >=1
    - pillow
    - packaging

test:
  imports:
    - djangocms_text_ckeditor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/django-cms/djangocms-text-ckeditor
  summary: Text Plugin for django CMS with CKEditor support
  license: BSD-3-Clause AND GPL-2.0-or-later AND MIT
  license_file:
    - LICENSE
    - djangocms_text_ckeditor/static/djangocms_text_ckeditor/ckeditor/LICENSE.md
    - djangocms_text_ckeditor/static/djangocms_text_ckeditor/ckeditor/plugins/wsc/LICENSE.md
    - djangocms_text_ckeditor/static/djangocms_text_ckeditor/ckeditor/plugins/exportpdf/LICENSE.md
    - djangocms_text_ckeditor/static/djangocms_text_ckeditor/ckeditor/plugins/scayt/LICENSE.md
    - djangocms_text_ckeditor/static/djangocms_text_ckeditor/ckeditor/samples/toolbarconfigurator/font/LICENSE.txt
    - djangocms_text_ckeditor/static/djangocms_text_ckeditor/ckeditor/samples/toolbarconfigurator/lib/codemirror/LICENSE

extra:
  recipe-maintainers:
    - rxm7706
